// USER CONSTANTS
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

// GENERAl CONSTANTS
export const FETCHING = "FETCHING"
export const FETCHED = "FETCHED"
export const ERROR = "ERROR"

// CONTENT RELATED CONSTANT
export const CATEGORY_FETCHED = "CATEGORY_FETCHED"
export const CATEGORY_CONTENT_FETCHED = "CATEGORY_CONTENT_FETCHED"
export const CONTENT_DETAILS_FETCHED = "CONTENT_DETAILS_FETCHED"


